name: daily/schedule

on:
  schedule:
    - cron: '20 13 * * *' # 9pm in Singapore time (minus 8)
  push:
    branches:
      - schedule/*

jobs:
  logs-in-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Create config files
        run: |
          echo "${{ secrets.ENVIRONMENT_DEV }}" > src/config/environment.ts
          echo "${{ secrets.DATABASE_DEV }}" > src/config/database.ts

      - name: Initialise discord bot
        run: yarn start

  trigger-schedule:
    needs: logs-in-discord
    runs-on: ubuntu-latest

    steps:
      - name: 'Trigger schedule'
        run: 'yarn trigger:schedule'
